### PR TITLE
Adding steps to terminate grunt and Vagrant session

### PR DESCRIPTION
**Pull request by bettymakes**
Also revised first step for working on existing projects to include "vagrant up". What do you think about adding those steps in both "Creating a new project" and "Working on Existing Projects"? 

Alternatively, I was thinking we could create a new section called "Terminating your session" and moving the last three steps into a section of its own.

Thoughts?

### CODE REVIEW

**Comment by fightingtheboss** [comment]
I think putting it into a section of its own is a better idea. I also need to add one more (very ugly) line to the initial setup. 

Before the first time you run `vagrant up` you will need to run this crazy thing on the command line:
`VBoxManage dhcpserver remove --netname HostInterfaceNetworking-vboxnet0`

It's a one time thing, but it will remove a known issue mainly for OS X and Linux users, but might help with Windows as well, gonna test soon.

Can you make the changes?

**Comment by bettymakes** [comment]
Done :). Added in the `VBoxManage dhcpserver remove --netname HostInterfaceNetworking-vboxnet0` command in the Setup section. Moved the termination steps into its own section. Take a look, let me know if there's anything else. 

I considered making a gif for each section but the gifs turned out to be massive files because the initial `vagrant up` command took a while to run. It also took a while to download all the npm and bower dependencies for the "Create a new project" section. I could probably edit the gif but on second thought, I'm not sure if it adds much value to the README. 

Let me know what you think :)!

**Comment by fightingtheboss** [comment]
Looks good! I was contemplating changing "Run `VBoxManage...`" to "Copy and paste `VBoxManage...`" before we merge it in. What do you think?

**Comment by bettymakes** [comment]
Sounds good to me :). Adjusted phrasing!

**Pull request merged**
